import type { LLMProviderAdapter, ProviderCallParams, ProviderCallResult } from "../client";

type ParsedOrchestratorPrompt = {
  task?: string;
  context?: {
    currentTickets?: Array<{
      id?: string;
      title?: string;
      description?: string | null;
      status?: string;
      priority?: string;
      harness?: unknown;
    }>;
  };
};

function safeJsonParse(value: string): unknown {
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function buildHarness(label: string) {
  return {
    goal: `${label} implementation outcome`,
    inputs: [
      `${label} project context`,
      `${label} API and DB constraints`,
      `${label} prior planning decisions`,
    ],
    output_format: [
      `${label} code and route behavior`,
      `${label} persisted state changes`,
      `${label} visible UI state update`,
    ],
    acceptance_checks: [
      `${label} flow is user-verifiable`,
      `${label} no schema validation errors`,
      `${label} event timeline reflects change`,
    ],
    non_goals: [`${label} excludes unrelated UX polish`, `${label} excludes unrelated refactors`],
    risks: [
      `${label} can regress ownership checks if route guards are changed`,
      `${label} can fail if event payload contracts drift`,
    ],
    test_ideas: [
      `${label} integration test through API routes`,
      `${label} smoke test through dashboard UI`,
    ],
  };
}

function buildGeneratePlanPayload() {
  const titles = [
    "E2E Seed: Scaffold project shell",
    "E2E Seed: Implement auth guard integration",
    "E2E Seed: Build project creation flow",
    "E2E Seed: Add orchestrator generate route coverage",
    "E2E Seed: Persist ticket version snapshots",
    "E2E Seed: Add event timeline ingestion",
    "E2E Seed: Wire replan apply engine",
    "E2E Seed: Render rationale diff view",
  ];

  return {
    createTickets: titles.map((title, index) => ({
      title,
      description: `Deterministic ticket ${index + 1} created by the test LLM provider.`,
      priority: index < 2 ? "HIGH" : "MEDIUM",
      harness: buildHarness(`ticket-${index + 1}`),
    })),
    updateTickets: [],
    closeTickets: [],
    rationale:
      "Initial deterministic plan generated by the test LLM provider for smoke/E2E coverage.",
  };
}

function isMutableTicketStatus(status: string | undefined): boolean {
  return status === "BACKLOG" || status === "TODO";
}

function buildReplanPayload(prompt: ParsedOrchestratorPrompt) {
  const currentTickets = Array.isArray(prompt.context?.currentTickets)
    ? prompt.context.currentTickets
    : [];
  const target =
    currentTickets.find((ticket) => isMutableTicketStatus(ticket.status)) ?? currentTickets[0];
  const ticketId = target?.id ?? "missing-ticket-id";
  const originalTitle = target?.title ?? "Untitled ticket";
  const originalDescription = target?.description ?? "No description";

  return {
    createTickets: [],
    updateTickets: [
      {
        ticketId,
        title: `${originalTitle} [Replanned]`,
        description: `${originalDescription}\n\nReplanned because a recent manual ticket edit changed implementation constraints.`,
        priority: "HIGH",
        harness: buildHarness("replan-adjustment"),
        reason: "Recent TICKET_UPDATED event changed priorities and acceptance focus.",
      },
    ],
    closeTickets: [],
    rationale:
      "Replan incorporated recent manual edits and adjusted at least one mutable ticket with updated implementation guidance.",
  };
}

function buildAgentPayload() {
  return {
    schemaVersion: 1,
    role: "IMPLEMENTER",
    summary: "Deterministic test provider implementer worklog.",
    status: "COMPLETED",
    findings: ["Core update path executed."],
    risks: ["Minimal synthetic output risk."],
    suggestedNextSteps: ["Run regression assertions."],
    replanSignal: {
      shouldReplan: false,
      severity: "LOW",
      reason: "No replan needed for this synthetic agent response.",
    },
    implementationPlan: ["Use deterministic payloads in tests."],
    touchedAreas: ["test-only provider boundary"],
    technicalRisks: ["Schema drift can break deterministic fixtures."],
    testSuggestions: ["Validate JSON schema compatibility in unit tests."],
  };
}

function buildResponseObject(params: ProviderCallParams): Record<string, unknown> {
  if (params.userPrompt.includes("Return a very short ticket summary for building login")) {
    return {
      summary: "Deterministic verify output",
      priority: "P1",
      risks: ["Synthetic provider output", "Schema mismatch risk if verify schema changes"],
    };
  }

  const parsedUserPrompt = safeJsonParse(params.userPrompt);
  const parsedPrompt: ParsedOrchestratorPrompt =
    parsedUserPrompt && typeof parsedUserPrompt === "object"
      ? (parsedUserPrompt as ParsedOrchestratorPrompt)
      : {};
  const task = typeof parsedPrompt.task === "string" ? parsedPrompt.task : "";

  if (task.includes("Generate the initial MVP implementation ticket plan")) {
    return buildGeneratePlanPayload();
  }

  if (task.includes("Use recent events and current tickets to produce a replan")) {
    return buildReplanPayload(parsedPrompt);
  }

  if (task.includes("Execute one focused ticket analysis and return a structured agent worklog")) {
    return buildAgentPayload();
  }

  return {
    ok: true,
    note: "Test provider fallback payload",
  };
}

export class TestProviderAdapter implements LLMProviderAdapter {
  provider = "test" as const;
  defaultModel = "test-deterministic-v1";

  async generateRawText(params: ProviderCallParams): Promise<ProviderCallResult> {
    const object = buildResponseObject(params);
    const rawText = JSON.stringify(object);

    return {
      provider: this.provider,
      model: params.model || this.defaultModel,
      rawText,
      inputTokens: 1,
      outputTokens: Math.max(1, Math.ceil(rawText.length / 10)),
    };
  }
}
